# #################
# Build and testing pipeline for Android
# #################

name: Android Build and Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  job-checkout-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests with Gradle
      run: ./gradlew test
      if: always()
      
    # The following check can be removed as soon as the unit tests are implemented
    - name: Check if test results are missing
      id: generate-notices
      run: |
        if [ ! -d "test-results" ]; then
          echo "::error::Directory test-results is missing."
          echo 'false'
        else
          echo 'true'
        fi      
      
    - name: Publish Test Results
      if: steps.generate-notices.outputs.commit == 'false'
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "test-results/**/*.xml"
