# #################
# Build and testing pipeline for Android
# #################

name: Android Build and Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  job-checkout-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests with Gradle
      run: ./gradlew test --stacktrace
      # if: always()

    - name: Unit test results check
      uses: actions/upload-artifact@v3
      with:
        name: unit-tests-results
        path: app/build/reports/tests/testDebugUnitTest/index.html

    - name: Generate APK
      run: ./gradlew assembleRelease --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/apk/release/*.apk



